-- ============================================
-- SEED DATA FOR RECYCLING MANAGER SELECTION
-- 40 Candidates with Evaluations
-- ============================================

-- Insert Candidates
INSERT INTO candidates (name, years_experience, skills) VALUES
('Kenneth Davis', 1, '["Risk Assessment", "Recycling Technologies", "Production Planning", "Quality Control", "Performance Management", "Process Optimization"]'),
('Donna Ramirez', 2, '["Process Optimization", "Safety Auditing", "Risk Assessment", "Conflict Resolution"]'),
('Joshua Johnson', 18, '["Contamination Control", "Equipment Maintenance", "Performance Management", "Carbon Footprint Analysis", "Risk Assessment"]'),
('Mark Nguyen', 9, '["Recycling Technologies", "OSHA Compliance", "Contamination Control", "Carbon Footprint Analysis"]'),
('Nancy Moore', 5, '["Recycling Technologies", "Waste Reduction", "Quality Control", "Process Optimization", "Environmental Compliance"]'),
('Michael Thompson', 12, '["Emergency Response", "Six Sigma", "Green Manufacturing", "Performance Management", "Quality Control", "Environmental Compliance", "Process Optimization", "Materials Sorting"]'),
('Christopher Green', 20, '["Cross-functional Collaboration", "Safety Auditing", "Contamination Control", "Process Optimization", "Six Sigma", "Risk Assessment"]'),
('Christopher Garcia', 8, '["Environmental Compliance", "Emergency Response", "Green Manufacturing", "Equipment Maintenance"]'),
('Lisa Hernandez', 12, '["Safety Auditing", "Materials Sorting", "Emergency Response", "Yield Optimization", "Equipment Maintenance", "Process Optimization"]'),
('Joshua Green', 6, '["Yield Optimization", "Risk Assessment", "OSHA Compliance", "Green Manufacturing", "Environmental Compliance", "Emergency Response", "Performance Management", "Recycling Technologies"]'),
('Amanda Lee', 2, '["Six Sigma", "Waste Reduction", "Environmental Compliance", "Emergency Response", "Process Optimization"]'),
('Susan Torres', 11, '["Equipment Maintenance", "Team Building", "Environmental Compliance", "Green Manufacturing", "Production Planning"]'),
('Thomas Rodriguez', 8, '["Performance Management", "Emergency Response", "Cross-functional Collaboration", "Carbon Footprint Analysis", "Contamination Control", "Environmental Compliance", "Circular Economy", "Risk Assessment"]'),
('William Allen', 16, '["Recycling Technologies", "Six Sigma", "Quality Control", "Production Planning"]'),
('Kenneth Hernandez', 14, '["Process Optimization", "Environmental Compliance", "Yield Optimization", "Change Management", "Green Manufacturing", "Conflict Resolution", "Emergency Response", "Performance Management"]'),
('James Baker', 4, '["Recycling Technologies", "Emergency Response", "Equipment Maintenance", "Waste Reduction", "Quality Control", "PPE Management", "Carbon Footprint Analysis", "OSHA Compliance"]'),
('Sandra Smith', 9, '["Recycling Technologies", "OSHA Compliance", "Conflict Resolution", "Quality Control", "Equipment Maintenance", "PPE Management", "Contamination Control", "Safety Auditing"]'),
('Barbara White', 6, '["Recycling Technologies", "Conflict Resolution", "Lean Manufacturing", "Change Management", "Waste Reduction", "Team Building", "Contamination Control", "Quality Control"]'),
('Lisa Martin', 8, '["Risk Assessment", "Cross-functional Collaboration", "Process Optimization", "Yield Optimization"]'),
('Ashley Jones', 18, '["Production Planning", "Materials Sorting", "Team Building", "Performance Management", "OSHA Compliance"]'),
('Thomas King', 20, '["Safety Auditing", "Performance Management", "Contamination Control", "Recycling Technologies", "PPE Management", "Environmental Compliance", "Circular Economy"]'),
('Mark King', 15, '["Risk Assessment", "Process Optimization", "Waste Reduction", "Lean Manufacturing"]'),
('Donna Scott', 8, '["Risk Assessment", "Lean Manufacturing", "Process Optimization", "Equipment Maintenance", "Six Sigma", "Recycling Technologies", "Contamination Control", "Materials Sorting"]'),
('Nancy Jones', 17, '["Emergency Response", "Materials Sorting", "Team Building", "Safety Auditing", "Performance Management"]'),
('William Campbell', 19, '["Team Building", "Risk Assessment", "Recycling Technologies", "Carbon Footprint Analysis", "Safety Auditing", "Quality Control", "Change Management", "Materials Sorting"]'),
('Daniel Ramirez', 14, '["Yield Optimization", "Six Sigma", "Materials Sorting", "Equipment Maintenance", "Contamination Control", "Quality Control", "Recycling Technologies"]'),
('Margaret Campbell', 11, '["Risk Assessment", "Safety Auditing", "Performance Management", "Green Manufacturing"]'),
('William Ramirez', 6, '["Green Manufacturing", "Risk Assessment", "Process Optimization", "Recycling Technologies", "Performance Management", "Quality Control"]'),
('Patricia Adams', 18, '["Process Optimization", "Recycling Technologies", "Risk Assessment", "OSHA Compliance"]'),
('Anthony Young', 16, '["Environmental Compliance", "Six Sigma", "OSHA Compliance", "Lean Manufacturing", "Emergency Response"]'),
('Sandra Jackson', 14, '["Materials Sorting", "Contamination Control", "Team Building", "Production Planning", "Safety Auditing", "PPE Management", "Equipment Maintenance", "Six Sigma"]'),
('Donna Mitchell', 18, '["Yield Optimization", "Waste Reduction", "Six Sigma", "Cross-functional Collaboration"]'),
('Donald Allen', 17, '["Six Sigma", "Conflict Resolution", "Process Optimization", "OSHA Compliance", "Change Management"]'),
('Robert Baker', 8, '["Quality Control", "Cross-functional Collaboration", "Risk Assessment", "Yield Optimization", "Change Management", "Six Sigma", "Process Optimization"]'),
('Anthony Nelson', 19, '["Conflict Resolution", "Waste Reduction", "Emergency Response", "Safety Auditing", "Yield Optimization", "Risk Assessment", "Contamination Control", "Environmental Compliance"]'),
('William Nelson', 10, '["Waste Reduction", "Process Optimization", "Lean Manufacturing", "Green Manufacturing", "Change Management", "Cross-functional Collaboration", "Quality Control"]'),
('Robert Wright', 7, '["Emergency Response", "Production Planning", "Circular Economy", "Process Optimization", "Risk Assessment", "Contamination Control", "PPE Management", "OSHA Compliance"]'),
('Mark Wright', 10, '["Equipment Maintenance", "Conflict Resolution", "Lean Manufacturing", "Materials Sorting", "Performance Management", "PPE Management", "Quality Control", "Production Planning"]'),
('Thomas Davis', 4, '["Production Planning", "Emergency Response", "PPE Management", "Change Management", "Safety Auditing", "Waste Reduction", "Equipment Maintenance", "Yield Optimization"]'),
('Steven Young', 9, '["Process Optimization", "Equipment Maintenance", "Carbon Footprint Analysis", "Emergency Response"]');

-- Insert Evaluations
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES
(1, 73, 52, 77),
(2, 98, 58, 89),
(3, 100, 100, 100),
(4, 92, 100, 90),
(5, 73, 92, 60),
(6, 97, 91, 100),
(7, 100, 100, 100),
(8, 80, 98, 67),
(9, 100, 85, 92),
(10, 99, 81, 90),
(11, 68, 70, 63),
(12, 93, 100, 100),
(13, 100, 100, 82),
(14, 100, 91, 86),
(15, 100, 100, 100),
(16, 71, 84, 82),
(17, 100, 96, 100),
(18, 85, 96, 100),
(19, 90, 95, 100),
(20, 100, 100, 100),
(21, 100, 100, 100),
(22, 100, 100, 80),
(23, 81, 89, 95),
(24, 100, 100, 100),
(25, 100, 100, 100),
(26, 100, 100, 100),
(27, 99, 95, 92),
(28, 100, 99, 80),
(29, 100, 100, 81),
(30, 100, 100, 87),
(31, 100, 100, 100),
(32, 100, 100, 100),
(33, 100, 100, 100),
(34, 93, 73, 81),
(35, 100, 100, 100),
(36, 90, 93, 100),
(37, 76, 100, 88),
(38, 98, 81, 100),
(39, 94, 85, 94),
(40, 100, 100, 78);

-- Trigger will auto-populate rankings table
-- ============================================
